checks:
    python:
        code_rating: true
        duplicate_code: true
build:
    environment:
        python:
            version: "3.7.1"
            # Whether to setup a virtualenv in the repository root directory.
            virtualenv: true
    dependencies:
        before:
            - python -m pip install --upgrade pip
            - pip install --upgrade setuptools
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - py-scrutinizer-run
                    -
                        command: pylint-run
                        use_website_config: true
        tests: true
filter:
    excluded_paths:
        - '*/test/*'
    dependency_paths:
        - 'lib/*'
